### ISSUE TITLE
SPIKE: Puppet Agent Container + PDK Gems

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/pdkgo#164]
- [x] Use puppet-agent base container
- [x] Install the PDK runtime gems on top of this
- [x] Ruby commands can be run within this container (called externally)
- [x] Document pros / cons for the PoC for evaluation from team after

**Comment by sanfrancrisko** [comment]
- [ ] Use puppet-agent base container
- [ ] Install the PDK runtime gems on top of this
- [ ] Ruby commands can be run within this container (called externally)
- [ ] Document pros / cons for the PoC for evaluation from team after

**Comment by michaeltlombardi** [comment]
### Experiment Notes 2021-09-13

Went to pursue a minimal experimental container which is built from the public `puppet/puppet-agent` container, using this dockerfile:

```dockerfile
FROM puppet/puppet-agent
RUN gem install pdk
RUN apt-get update && apt-get install build-essential libssl-dev libyaml-dev zlib1g-dev libffi-dev -y
ENTRYPOINT ["/opt/puppetlabs/puppet/bin/pdk"]
CMD ["validate"]
```

If I navigate to any puppet module on my system, from inside that module folder I can run:

```bash
docker run -it  -v ${PWD}:/module -w /module pdkdocker
```

and it will display the expected validation behavior, using the appropriate ruby/puppet, downloading any missing dependencies, and running all the validators.

The image size (entirely unoptimized) is 479MB - large, but manageable. 

It is also possible to install any/all native compiled gems, including pry.

I also experimented with calling `gem install puppet-strings`, which then allowed me to call `puppet strings` as expected.

Initial thoughts:

- This could work really well for ubuntu agents; it gets us away from having to build the ruby runtime ourselves
- We will have to figure out mac containers (if we want to) and Windows containers for ourselves - luckily I think the latter should be very straightforward and we might even be able to get the Puppet Agent repo to take ownership of a base image if we contribute it
- We will be pinned to only supporting whatever releases of Puppet Agent get containerized which is good because that's all we care about
- We could ship multiple versions of these containers: with/without dev tools, with/without everything pre-installed
- The main thing to note for us is we'll always want to mount the folder somewhere reliable and set it as the working directory, which I think we can abstract in our go code easily enough.
- This will *require* that the end user have Docker and access to either the public docker repo or their own mirror
- This can be consumed neatly inside of a GitHub Action
- This iteration did a very simplistic install of the PDK in order to get current functionality, but we may want to think about an alternate method (or maybe a new metagem that includes whatever runtime deps we care about?)
- The Puppet Agent containers have a specific version tag, including `6.y.z` / `7.y.z` and a `latest` tag which is an alias of the newest `7.y.z` but not a `6x` or `7x` tag - we may need to do some work around this on our end and may just want to build our own tags pinned to whatever those versions are that can be found on the registry.

### Summary Thoughts

I think this is a fairly strong contender for our solution, assuming a docker-based solution is going to be functional for us at all - it's xplat, low lift (we maintain an additional set of dockerfiles and rebuild when upstream gets built) and manage via our own minimal interface eventually but _initially_ we can just document how to use the dockerfiles directly. These dockerfiles could also be used as VSCode dev containers without too much issue, I think.

**Comment by michaeltlombardi** [comment]
## Experiment Notes 2021-09-15

Went to see how much work it would be to build our own Windows container that installs the Puppet agent and PDK gems; eventually, I think the windows container's base (ie just adding Puppet agent) could be moved upstream to puppetlabs/puppet-agent which would be a boon for everyone.

I got to an 80% effective solution:

```dockerfile
FROM mcr.microsoft.com/windows:20H2
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ADD https://downloads.puppetlabs.com/windows/puppet/puppet-agent-x64-latest.msi C:\\puppet.msi
RUN mkdir C:\Puppet ; msiexec /qn /norestart /i C:\puppet.msi INSTALLDIR=C:\Puppet
ADD https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe C:\\msys2.exe
RUN "C:\\msys2.exe -y -oC:\\"

RUN Remove-Item C:\msys2.exe ; \
  function msys() { C:\msys64\usr\bin\bash.exe @('-lc') + @Args; } \
  msys ' '; \
  msys 'pacman --noconfirm -Syuu'; \
  msys 'pacman --noconfirm -Syuu'; \
  msys 'pacman --noconfirm -Scc'; \
  msys 'pacman --noconfirm -S autoconf autogen automake-wrapper diffutils file gawk grep libtool m4 make patch sed texinfo texinfo-tex wget'; \
  msys 'pacman --noconfirm -S mingw-w64-x86_64-binutils mingw-w64-x86_64-crt-git mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-headers-git mingw-w64-x86_64-libmangle-git mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-make mingw-w64-x86_64-tools-git mingw-w64-x86_64-winpthreads-git pkgconf mingw-w64-x86_64-pkgconf'
  # The line above installs x64 build tools, the line below x32
  # msys 'pacman --noconfirm -S mingw-w64-i686-binutils mingw-w64-i686-crt-git mingw-w64-i686-gcc mingw-w64-i686-gcc-libs mingw-w64-i686-headers-git mingw-w64-i686-libmangle-git mingw-w64-i686-libwinpthread-git mingw-w64-i686-make mingw-w64-i686-tools-git mingw-w64-i686-winpthreads-git pkg-config mingw-w64-pkg-config'

# Make sure Puppet's vendored ruby/gem are available on the path
RUN setx path "'%PATH%;C:\\Puppet\\puppet\\bin'"

ENTRYPOINT [ "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" ]
# RUN gem install pdk
# RUN apt-get update && apt-get install build-essential libssl-dev libyaml-dev zlib1g-dev libffi-dev -y
# ENTRYPOINT ["/opt/puppetlabs/puppet/bin/pdk"]
# CMD ["validate"]
```

Where this gets us:

1. Puppet Agent is installed/available
2. Msys2 and the build tool packages are all installed
3. We can build nokogiri but _not_ http-parser for some reason; this matters because http-parser is a dep for honeycomb-beeline which means this will blow up when bundle installing for any IAC module
4. We can't use the naive `gem install pdk` because the vendored facter from Puppet Agent will conflict with the gem install facter
5. The container is _giant_, 17.2GB - could definitely be slimmed down with windows server core but there's some constraints around which images my machine can build/run bc of OS versions and the way these containers work
6. The container is _slow_, a noticeable longer-than-a-second pause at spin up and spin down

### Summary Thoughts

This route is promising for the Windows container but there's definitely still dragons to fight. If we can get the native gem compilation stuff to work I think we can definitely slim the image down and address everything else.

**Comment by michaeltlombardi** [comment]
Decided on this as the way forward, everything noted here is addressable.
